upgrade laravel amqp library
softonic/laravel-transactional-event-publisher pull request #21
Opened 2022-11-10 13:38 UTC by Serginyu

2022-11-10 13:46 UTC, jeurrutia approved these changes

2022-11-10 13:48 UTC, jeurrutia requested changes
The php version should be changed in the composer.json (Scrutinizer failed)

2022-11-10 14:36 UTC, xaviapa approved these changes

2022-11-11 09:08 UTC, joskfg commented
I think we should update the library skeleton to use actions and normalize with other libraries.

2022-11-14 13:39 UTC, joskfg approved these changes

2022-11-14 13:56 UTC, merged